table FilterRevenueTable
	lineageTag: d6cdd2a8-b516-4d29-bf2a-4a3e604c3f18

	column FilterRevenue
		dataType: string
		lineageTag: 8d5fde37-5fc4-42ec-967c-99cbd7b64779
		summarizeBy: none
		sourceColumn: FilterRevenue
		sortByColumn: SortRevenue

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column SortRevenue
		dataType: int64
		formatString: 0
		lineageTag: 63e48d96-16b2-4460-ae9d-ea6192f3a9b0
		summarizeBy: sum
		sourceColumn: SortRevenue

		annotation SummarizationSetBy = Automatic

	partition FilterRevenueTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wci/KLy5W0lEyVIrViVbySy0Bso3A7ICi/LRMENdYKTYWAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [FilterRevenue = _t, SortRevenue = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"FilterRevenue", type text}, {"SortRevenue", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

