table TimeFilterTable
	lineageTag: 85576205-af05-4e73-ac1d-4eba326f9b5e

	column TimeFilter
		dataType: string
		lineageTag: 88ad971e-5905-40a5-808a-44d88b9450e8
		summarizeBy: none
		sourceColumn: TimeFilter
		sortByColumn: TimeValues

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column TimeValues
		dataType: int64
		formatString: 0
		lineageTag: d4d5cd0d-b18a-45c5-b8ec-8cc5519d2b8d
		summarizeBy: sum
		sourceColumn: TimeValues

		annotation SummarizationSetBy = Automatic

	partition TimeFilterTable = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlZwSawsVtJRMlaK1YlWModxzcFcYwO4tAFYwFAhMjWxCMQ3MwULhOSXJOaA5Q2AKmIB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [TimeFilter = _t, TimeValues = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"TimeFilter", type text}, {"TimeValues", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

